### PR TITLE
Support modifying responses

### PR DESCRIPTION
**Pull request by adalinesimonian**
Most significantly, this adds support for modifying responses. This is extremely useful when:

- Proxying a service that has its URL hardcoded, which needs to be replaced with the proxy URL so that links and references function properly.
- Modifying the behaviour of an existing application or service in situations where there is no alternative.

This functionality makes this library even more powerful.

Here's an example of usage:

```csharp
new ProxyRule {
    // ...
    Modifier = (req, user) => {
        req.RequestUri = new Uri(
            $"https://www.example.com{req.RequestUri.PathAndQuery}"
        );
    },
    ResponseModifier = async (msg, ctx) =>
    {
        ctx.Response.Headers.Remove("Strict-Transport-Security");
        ctx.Response.Headers.Remove("Content-Security-Policy");
        if (msg.StatusCode == System.Net.HttpStatusCode.OK)
        {
            switch (msg.Content.Headers.ContentType.MediaType)
            {
                case "text/html":
                case "application/xhtml+xml":
                case "application/javascript":
                case "text/css":
                    var body = Regex.Replace(
                        await msg.Content.ReadAsStringAsync(),
                        @"(http(s)?:)?//(?:www\.)?example.com",
                        string.Format(
                            "{0}://{1}",
                            ctx.Request.Scheme,
                            ctx.Request.Host
                        ),
                        RegexOptions.IgnoreCase
                    );
                    byte[] data = Encoding.UTF8.GetBytes(body);
                    ctx.Response.ContentLength = data.Length;
                    await ctx.Response.Body.WriteAsync(data, 0, data.Length);
                    break;
                default:
                    await msg.Content.CopyToAsync(ctx.Response.Body);
                    break;
            }
        }
        else
        {
            await msg.Content.CopyToAsync(ctx.Response.Body);
        }
    }
}
```

This PR also adds the `PreProcessResponse` boolean, with a default value of `false`. If set to true, and a delegate is specified for `ResponseModifier`, default operations that modify the response sent to the user agent (such as copying headers from the originating server) are skipped.

**Overview of all changes:**

- Added support for modifying response with `ProxyRule.ResponseModifier`
- Added support for skipping default response processing with `ProxyRule.PreProcessResponse`
- Bumped version to 1.3.0
- Updated projects to CSPROJ format
- Updated solution to latest format (VS2017)
- Updated dependencies
- Tagged SharpReverseProxy.Tests.csproj as a test project
- Target .NET Standard 1.6
- Sample applications target .NETCoreApp 1.1
- Solution updated to latest format
- Fixed typo: `ProxyStatus.Elipsed` deprecated in favour of replacement `ProxyStatus.Elapsed`

### CODE REVIEW

**Comment by andrecarlucci** [comment]
Hi @vsimonian, really nice idea about modifying the response too.
Do you think you could add some unit tests for the code you have written?
I'm already ashamed about the amount of tests we have right now, so I'm trying to add more as  the code is modified.
Thanks a lot for the PR!

**Comment by adalinesimonian** [comment]
I don't mind at all; I can throw some tests in. 👍

**Comment by adalinesimonian** [comment]
Threw a test in and fixed a regression. Please let me know what you think!

**Comment by andrecarlucci** [comment]
Nuget is up! Thanks a lot, @vsimonian :)

**Pull request merged**
